---
title: "[Q#13239972][A#13239999] How do you implement a re-try-catch?"
question_title: "How do you implement a re-try-catch?"
question_text: "Try-catch is meant to help in the exception handling. This means somehow that it will help our system to be more robust: try to recover from an unexpected event. We suspect something might happen when executing and instruction (sending a message), so it gets enclosed in the try. If that something nearly unexpected happens, we can do something: we write the catch. I don't think we called to just log the exception. I thing the catch block is meant to give us the opportunity of recovering from the error. Now, let's say we recover from the error because we could fix what was wrong. It could be super nice to do a re-try: This would quickly fall in the eternal loop, but let's say that the fix_the_problem returns true, then we retry. Given that there is no such thing in Java, how would YOU solve this problem? What would be your best design code for solving this? This is like a philosophical question, given that I already know what I'm asking for is not directly supported by Java."
answer_text: "You need to enclose your try-catch inside a while loop like this: - I have taken count and maxTries to avoid running into an infinite loop, in case the exception keeps on occurring in your try block."
apization_code: "package com.stackoverflow.api;  /**  * How do you implement a re-try-catch?  *  * @author APIzator  * @see <a href=\"https://stackoverflow.com/a/13239999\">https://stackoverflow.com/a/13239999</a>  */ public class APIzator13239999 {    public static void implementCatch(int maxTries) throws RuntimeException {     int count = 0;     while (true) {       try {         // Some Code         // break out of loop, or return, on success       } catch (SomeException e) {         // handle exception         if (++count == maxTries) throw e;       }     }   } }"
---

https://stackoverflow.com/q/13239972

Try-catch is meant to help in the exception handling. This means somehow that it will help our system to be more robust: try to recover from an unexpected event.
We suspect something might happen when executing and instruction (sending a message), so it gets enclosed in the try. If that something nearly unexpected happens, we can do something: we write the catch. I don&#x27;t think we called to just log the exception. I thing the catch block is meant to give us the opportunity of recovering from the error.
Now, let&#x27;s say we recover from the error because we could fix what was wrong. It could be super nice to do a re-try:
This would quickly fall in the eternal loop, but let&#x27;s say that the fix_the_problem returns true, then we retry. Given that there is no such thing in Java, how would YOU solve this problem? What would be your best design code for solving this?
This is like a philosophical question, given that I already know what I&#x27;m asking for is not directly supported by Java.


<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
try{ some_instruction(); }
catch (NearlyUnexpectedException e){
   fix_the_problem();
   retry;
}
```


## Original code snippet

https://stackoverflow.com/a/13239999

You need to enclose your try-catch inside a while loop like this: -
I have taken count and maxTries to avoid running into an infinite loop, in case the exception keeps on occurring in your try block.

<div class="code-logo"><img src="/stackoverflow.png" /></div>

```java
int count = 0;
int maxTries = 3;
while(true) {
    try {
        // Some Code
        // break out of loop, or return, on success
    } catch (SomeException e) {
        // handle exception
        if (++count == maxTries) throw e;
    }
}
```

## Produced APIzation

[`APIzator13239999.java`](https://github.com/pasqualesalza/apization-temp-data/raw/master/search/APIzator13239999.java)

<div class="code-logo"><img src="/apizator.png" /></div>

```java
package com.stackoverflow.api;

/**
 * How do you implement a re-try-catch?
 *
 * @author APIzator
 * @see <a href="https://stackoverflow.com/a/13239999">https://stackoverflow.com/a/13239999</a>
 */
public class APIzator13239999 {

  public static void implementCatch(int maxTries) throws RuntimeException {
    int count = 0;
    while (true) {
      try {
        // Some Code
        // break out of loop, or return, on success
      } catch (SomeException e) {
        // handle exception
        if (++count == maxTries) throw e;
      }
    }
  }
}

```